sudo: false
language: generic
branches:
  only:
    - source
env:
  global:
    - GH_REPO="dpwright/dpwright.github.com"
    - secure: ljOo/ngWTRMbbXyvkZaXKXZG+vIn+NxTqJnn3UBqgocVTQTmBGUwQ6xYyoOOy4eYg9Ezsm6R490xNJFcVtLpBcKF/iHlzXewwFwluFeVD750vlo98UtqEGkW8/rku+Q+uqAcOiSXulHGdwei/QB/9Wa5RV4+EGqsxvZMcJl4EAk=
    - REPO_URL="https://$GH_TOKEN@github.com/$GH_REPO.git"
cache:
  directories:
    - $HOME/.stack
addons:
  apt:
    packages:
      - libgmp-dev
before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
install:
  - travis_wait 50 stack -j2 --no-terminal --install-ghc build --only-dependencies
before_script:
  - cd _site
  - git checkout master
  - git pull origin master
  - rm -rf *
  - cd ..
script:
  - stack --no-terminal build
  - stack --no-terminal exec site build
after_success:
  - cd _site
  - git status
  - git add -A
  - git config --global user.email "dani@dpwright.com"
  - git config --global user.name "Daniel P. Wright"
  - git commit -m "Snapshot $(date '+%m/%d/%y %H:%M')"
  - git push "$REPO_URL" master | grep -v http
  - cd ..
